### ISSUE TITLE
请问这个如何部署

### ISSUE THREAD

**Issue by xau0at** [haihuiling/wechat-kindle#1]
我之前是部署在[sae](http://sae.sina.com.cn/)上面，创建一个应用，然后把代码丢进去就可以了，但是好像忘记上传sql了。。。。

**Comment by haihuiling** [comment]
我之前是部署在[sae](http://sae.sina.com.cn/?m=dashboard)上面，创建一个应用，然后把代码丢进去就可以了，但是好像忘记上传sql了。。。。

**Comment by xau0at** [comment]
能上传一下吗 谢谢

**Comment by bujnlc8** [comment]
不好意思啊，我找了很久也没找到备份的，欠费了线上的都被新浪清空了。实在是抱歉。

**Comment by xau0at** [comment]
@haihuiling  谢谢，给你添麻烦了。
